@startuml MLD-DataBase
skinparam style strictuml
skinparam packageStyle rect
skinparam defaultfontname xkcd Script
hide empty members

entity Membre{
    * id_membre : number <<PK>>
    * id_geniALE : number <<FK>>
    * id_departement : number <<FK>>
    date_admission : date
}

entity geniALE{
    * id_geniALE : number <<PK>>
    nom : varchar
    penom : varchar
    linkedin : varchar <<UQ>>
    photo : varchar
}

entity Executif{
    * id_executif : number <<PK>>
    * id_geniALE : number <<FK>>
    * id_departement : number <<FK>>
    poste : varchar <<UQ>>
    description : varchar  
}
entity Departement{
    * id_departement : number <<PK>>
    nom : varchar<<UQ>>
    description : varchar
}
entity NosBieres{
    * id_nosBiere : number <<PK>>
    nom : varchar
    description : varchar
    date : date 
}

entity NotationBiere{
    * id_notation : number <<PK>>
    * id_nosBiere : number <<FK>>
    note : number 
}

entity Photo{
    * id_photo : number(10) <<PK>>
    nom : varchar(100)
    taille : number(10)
    type : varchar(50)
    bin : blob(255)
}

entity Marchandise{
    * id_marchandise : number <<PK>>
    nom : varchar
    
}

entity EvenementPhoto{
    * id_evenement : number <<FK>>
    * id_photo : number <<FK>>
    photo : varchar
}

entity Evenement{
    * id_evenement : number <<PK>>
    nom : varchar
    description : varchar
    date : date
}

entity ParticipantEvenement{
    * id_evenement : number <<FK>>
    * id_participant : number <<FK>>
}

entity Participant{
    * id_participant : number <<PK>>
    nom : varchar
    prenom : varchar
    email : varchar
}







@enduml