@startuml MLD-DataBase
skinparam style strictuml
skinparam packageStyle rect
skinparam defaultfontname xkcd Script
hide empty members

entity Membre{
    * id_membre : number <<PK>>
    * id_geniALE : number <<FK>>
    * id_departement : number <<FK>>
    date_admission : date
}

entity GeniALE{
    * id_geniALE : number <<PK>>
    * id_calendrier : number <<FK>>
    nom : varchar
    prenom : varchar
    linkedin : varchar <<UQ>>
    photo : varchar   
}
'TODO: modifier le table pour qu'elle représente le calendrier de disponibilité 
entity Calendrier {
    * id_calendrier : number <<PK>>
    date : date <<UQ>>
    annee : number
    mois : number
    jour : number
}


entity Executif{
    * id_executif : number <<PK>>
    * id_geniALE : number <<FK>>
    * id_departement : number <<FK>>
    poste : varchar <<UQ>>
    description : varchar  
}
entity Departement{
    * id_departement : number <<PK>>
    nom : varchar<<UQ>>
    description : varchar
}
entity NosBieres{
    * id_nosBiere : number <<PK>>
    * id_photo : number <<FK>>
    nom : varchar
    description : varchar
    date_date_production : date 
}

entity NotationBiere{
    * id_notation : number <<PK>>
    * id_nosBiere : number <<FK>>
    * id_membre : number
    note : number 
}

entity Photo{
    * id_photo : number <<PK>>
    nom : varchar
    taille : number
    type : varchar
    bin : blob
}

entity Marchandise{
    * id_marchandise : number <<PK>>
    * id_photo : number <<FK>>
    nom : varchar
    description: varchar
    prix : number    
}

entity EvenementPhoto{
    * id_evenement : number <<FK>>
    * id_photo : number <<FK>>
    photo : varchar
}

entity Evenement{
    * id_evenement : number <<PK>>
    nom : varchar
    description : varchar
    date_event : date
}

entity ParticipantEvenement{
    * id_evenement : number <<FK>>
    * id_participant : number <<FK>>
}

entity Participant{
    * id_participant : number <<PK>>
    nom : varchar
    prenom : varchar
    email : varchar
}

entity EvenementCalendrier{
    * id_evenement : number <<FK>>
    * id_calendrier : number <<FK>>
}


GeniALE }|--|| Membre
GeniALE }|--|| Executif
Departement }|--|| GeniALE

GeniALE ||--|| Calendrier
EvenementCalendrier ||--|| Calendrier
EvenementCalendrier ||--|| Evenement

Participant ||--o{ ParticipantEvenement
ParticipantEvenement }o--|{ Evenement
EvenementPhoto }o--|{ Evenement

Photo }o--|{ EvenementPhoto
Photo }o--|{ NosBieres
Photo }o--|{ Marchandise

NosBieres }|--|| NotationBiere
@enduml